Cleanups.

diff --git a/.github/workflows/publish-dev.yaml b/.github/workflows/publish-dev.yaml
--- a/.github/workflows/publish-dev.yaml
+++ b/.github/workflows/publish-dev.yaml
@@ -37,13 +37,20 @@ jobs:
       # - If latest release is a development one, increment the '-dev.N' suffix by one
       - name: Resolve tag for release
         run: |
-          # Find the latest official release tag matching X.Y.Z format
-          latest_tag=$(git tag --sort=v:refname | grep -E '^[0-9]+\.[0-9]+\.[0-9]+$' | tail -n 1)
+          # Find the latest official release tag matching 'X.Y.Z' format
+          latest_official_tag=$(git tag --sort=v:refname | grep -E '^[0-9]+\.[0-9]+\.[0-9]+$' | tail -n 1)
+          if [ -z "$latest_official_tag" ]; then
+            echo "Error: Latest official release tag (X.Y.Z) not found!"
+            exit 1
+          fi
+          echo "Latest official release tag: $latest_official_tag"
+          echo "LATEST_RELEASE_TAG=$latest_official_tag" >> $GITHUB_ENV
 
-          # If no tag was found, default to 0.0.0
+          # Find the latest any release tag matching 'X.Y.Z.*' format
+          latest_tag=$(git tag --sort=v:refname | grep -E '^[0-9]+\.[0-9]+\.[0-9]+.*$' | tail -n 1)
           if [ -z "$latest_tag" ]; then
-            echo "Latest official release tag not found, default to 0.0.0"
-            latest_tag="0.0.0"
+            echo "Error: Latest release tag (official or dev) not found!"
+            exit 1
           fi
 
           # Check if $latest_tag has the '-dev.n' suffix.
